SELECT 
smn_base.smn_estructura_organizacional.smn_estructura_organizacional_id as id,
smn_base.smn_estructura_organizacional.eor_codigo||'-'||smn_base.smn_estructura_organizacional.eor_nombre as item 
from 
smn_base.smn_estructura_organizacional
INNER join smn_base.smn_configuracion_estructura on smn_base.smn_configuracion_estructura.smn_configuracion_estructura_id=
smn_base.smn_estructura_organizacional.smn_configuracion_estructura_id
INNER join smn_base.smn_rel_entidad_estructura on smn_base.smn_rel_entidad_estructura.smn_configuracion_estructura_id = smn_base.smn_estructura_organizacional.smn_configuracion_estructura_id
inner join smn_base.smn_entidades on smn_base.smn_entidades.smn_entidades_id = smn_base.smn_rel_entidad_estructura.smn_entidades_id
where
smn_base.smn_entidades.ent_descripcion_corta=${fld:id} and smn_base.smn_rel_entidad_estructura.rec_usuario='${def:user}' GROUP BY ID,ITEM ORDER BY ID DESC