select
	smn_gip.smn_documentos.smn_documentos_generales_rf as dcm_nombre,
	smn_control_acceso.smn_personal.psl_id_control_acceso,
	smn_gip.smn_tipo_actividades.tya_nombre,
		smn_control_acceso.smn_justificaciones.smn_justificaciones_id,
	smn_control_acceso.smn_justificaciones.jus_estatus_rf as jus_estatus_rf_pl0,
select
	smn_control_acceso.smn_justificaciones_soporte.smn_justificaciones_soporte_id,
	smn_control_acceso.smn_justificaciones_soporte.jsa_persona_rf,
	smn_control_acceso.smn_justificaciones_soporte.jsa_archivo,
	smn_control_acceso.smn_justificaciones_soporte.jsa_contenido,
	smn_control_acceso.smn_justificaciones_soporte.jsa_tamano,
	smn_control_acceso.smn_justificaciones_soporte.jsa_idioma,
	smn_control_acceso.smn_justificaciones_soporte.jsa_usuario,
	smn_control_acceso.smn_justificaciones_soporte.jsa_fecha_registro,
	smn_control_acceso.smn_justificaciones_soporte.jsa_hora
	
from
	smn_gip.smn_documentos,
	smn_control_acceso.smn_personal,
	smn_gip.smn_tipo_actividades,
	smn_control_acceso.smn_justificaciones,
	smn_control_acceso.smn_justificaciones_soporte
where
	smn_gip.smn_documentos.smn_documentos_id = smn_control_acceso.smn_justificaciones.jus_documento_rf and
	smn_control_acceso.smn_personal.smn_personal_id = smn_control_acceso.smn_justificaciones.jus_jefe_inmediato_rf and
	smn_gip.smn_tipo_actividades.smn_tipo_actividades_id = smn_control_acceso.smn_justificaciones.jus_tipo_actividad_rf and
	smn_justificaciones_soporte_id is not null
		and 	smn_control_acceso.smn_justificaciones.smn_justificaciones_id=smn_control_acceso.smn_justificaciones_soporte.smn_justificaciones_id
	
	${filter}
order by
		smn_justificaciones_soporte_id
