select
		smn_control_acceso.smn_carnet_identificacion.smn_carnet_identificacion_id,
	smn_control_acceso.smn_carnet_identificacion.cid_codigo,
	smn_control_acceso.smn_carnet_identificacion.cid_descripcion,
	smn_control_acceso.smn_carnet_identificacion.cid_estatus,
	smn_control_acceso.smn_carnet_identificacion.cid_fecha_vigente,
	smn_control_acceso.smn_carnet_identificacion.cid_fecha_registro
	
from
	smn_control_acceso.smn_carnet_identificacion
