select
	'' as dis_codigo,
	'' as dis_nombre,
	'' as dis_empresa,
	'' as dis_sucursal,
	'' as dis_area_servicio,
	'' as dis_unidad_servicio,	
	'' as dis_tipo_dispositivo_combo,
	'' as dis_serial,
	'' as dis_ip_address,
	'' as dis_empresa_reference,
	'' as dis_sucursal_reference,
	'' as dis_area_servicio_reference,
	'' as dis_unidad_servicio_reference,
	'' as dis_tipo_dispositivo_combo_reference
