INSERT INTO smn_control_acceso.smn_permisos_soporte
(
	smn_permisos_soporte_id,
	smn_solicitud_permisos_id,
	pma_persona_ref,
	pma_archivo,
	pma_datos_imagen,
	pma_tamano,
	pma_archivo,
	pma_contenido,
	pma_idioma,
	pma_usuario,
	pma_fecha_registro,
	pma_hora
)
VALUES
(
	${seq:nextval@smn_control_acceso.seq_smn_permisos_soporte},
	${fld:smn_solicitud_permisos_id},
	${fld:pma_persona_ref},
	${fld:_filename},
	?,
	${fld:_filesize},
	${fld:_filenametemp},
	${fld:_contenttype},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
