select
	'' as psl_num_control,
	'' as psl_clase_auxiliar,
	'' as psl_auxiliar,
	'' as psl_empresa,
	'' as psl_sucursal,
	'' as psl_area_servicio,	
	'' as psl_unidad_servicio,
	'' as psl_centro_costo,
	'' as psl_estructura_organiz,
	'' as psl_cargo,
	'' as psl_categoria_cargo,
	'' as psl_habilita_acceso,
	'' as psl_id_control_acceso,
	'' as psl_clase_auxiliar_reference,
	'' as psl_auxiliar_reference,
	'' as psl_empresa_reference,
	'' as psl_sucursal_reference,
	'' as psl_area_servicio_reference,	
	'' as psl_unidad_servicio_reference,
	'' as psl_centro_costo_reference,
	'' as psl_estructura_organiz_reference,
	'' as psl_cargo_reference,
	'' as psl_categoria_cargo_reference,
	'' as psl_habilita_acceso_reference

