select	
	smn_control_acceso.smn_personal.smn_personal_id as personal_id,
	smn_base.smn_auxiliar.aux_codigo ||' - '|| smn_base.smn_auxiliar.aux_descripcion as item
	
from
	smn_control_acceso.smn_plan_asistencia
	inner join smn_control_acceso.smn_personal on smn_control_acceso.smn_personal.psl_estructura_organizacional_rf=smn_control_acceso.smn_plan_asistencia.smn_estructura_organizacional_rf 
	and smn_control_acceso.smn_personal.psl_esquema_rotacion_rf=smn_control_acceso.smn_plan_asistencia.smn_esquema_rotacion_id
	inner join smn_base.smn_auxiliar on smn_base.smn_auxiliar.smn_auxiliar_id=smn_control_acceso.smn_personal.psl_auxiliar_rf
	left outer join smn_control_acceso.smn_plan_asistencia_personal on smn_control_acceso.smn_plan_asistencia_personal.smn_personal_id=smn_control_acceso.smn_personal.smn_personal_id
	and smn_control_acceso.smn_plan_asistencia_personal.smn_plan_asistencia_id=smn_control_acceso.smn_plan_asistencia.smn_plan_asistencia_id
	
where
	smn_control_acceso.smn_personal.smn_personal_id is not null 
	and smn_control_acceso.smn_plan_asistencia_personal.smn_personal_id is null
	and smn_control_acceso.smn_plan_asistencia.smn_plan_asistencia_id=${fld:id}
order by item 